feat: Toc 사이드바 제작
dev-wiki-kr/dev-wiki pull request #53
Opened 2024-06-09 21:51 UTC by im-na0

## 설명

close #15 
- h1 ~ h6까지 정보를 가져와서 목차를 구성한다.
- 목차 클릭시에 그에 해당하는 헤딩 태그로 스크롤이 이동할 수 있도록 한다.
- 스크롤 위치가 헤딩태그와 근접할 때 해당 목차 아이템을 하이라이팅한다.
- 헤딩의 숫자 부분에 앵커를 추가한다.

위 조건에 해당하는 목차 사이드바를 제작합니다.

## 변경 내역

- toc parser 유틸 구현
문서에서 `#`을 찾아 `heading level, text` 와 github slugger 통해 `slug` 생성해서 반환하는 함수입니다.
- 스크롤 위치가 헤딩태그와 근접할 때 해당 목차 아이템을 하이라이팅하도록 구현
- auto link headings 유틸 구현
헤딩 노드의 숫자부분은 a 태그로 감싸고, 문자 부분은 span 태그로 래핑하도록 구현했습니다.

- tsconfig `target: "esnext"` 추가
최신 자바스크립트 문법을 사용하기 위해 추가했습니다.

- 아코디언 초기화 중에도 펼쳐지도록 추가
아코디언의 모든 `id`를 순회해야 isExpand가 true로 설정되기 때문에 isExpand가 초기값인 경우 널리쉬 연산자를 통해 `expand = {isExpand ?? true}` 초기화 진행 중에도 펼쳐지도록 추가했습니다.

## 논의할 점

Toc 사이드바 반응형 작업이 필요합니다!

## 스크린샷
#### 스크롤 했을 때 toc 활성화
https://github.com/dev-wiki-kr/dev-wiki/assets/139189221/022bde03-4147-4cc5-aaf6-8f7a42afb83b

#### toc 클릭 했을 때 해당 헤딩태그로 이동
https://github.com/dev-wiki-kr/dev-wiki/assets/139189221/20e973c4-1843-4772-bd0b-78ca89a1d9e2

#### 앵커 태그로 이동
https://github.com/dev-wiki-kr/dev-wiki/assets/139189221/6c89602b-e8a7-42db-a715-a0f204e30bf3

2024-06-10 07:27 UTC, im-na0 commented on app/_shared/toc/toc-side.tsx
> +      const top = element ? element.getBoundingClientRect().top + scrollTop : Infinity
### ✅ 스크롤 위치에 따라 toc 아이템을 활성화하는 Flow
- 각각의 헤딩 ID의 절대적 위치 구함 👈
- 현재 스크롤 위치 구함
- 헤딩의 상단 위치가 현재 스크롤 위치보다 작거나 같을 때 해당 헤딩을 활성화 상태로 설정
- 이 상태를 사용하여 TOC 아이템을 활성화 또는 비활성화

이 코드는 각각의 heading id의 절대적 위치를 얻기 위해 각 요소의 `element.getBoundingClientRect().top`을 통해 요소가 뷰포트에서 얼마나 떨어져 있는지 측정하고, 현재 문서가 얼마나 스크롤되었는지 나타내는 `scrollTop`값을 더합니다. 요소가 존재하지 않는 경우에는 처리할 수 없으므로, 이러한 상황을 구별하기 위해 `Infinity` 값을 사용합니다.

2024-06-10 07:35 UTC, im-na0 commented on app/lib/auto-link-headings.ts
> +          node.children = [anchorLink, spaceNode, spanElement]
노드를 앵커 + 공백 텍스트 + span 로 구성하는 이유는 글머리 번호와 문자 사이 띄어쓰기가 필요해서 추가했습니당 
```html
<h3 id="24-확장성"><a class="anchor" href="#24-확장성">2.4.</a>{'여기공백'}<span>확장성</span></h3>
```

2024-06-12 06:31 UTC, Zalgritte commented
와 멋집니다! 스무스한 트랜지션도 좋아요
반응형은 오늘 얘기해보아요

2024-06-13 16:57 UTC, hwangstar156 requested changes

2024-06-13 16:57 UTC, hwangstar156 commented on app/_shared/accordion/accordion-title.tsx
> +    }
closest만으로 이러한 처리가 가능한가요? a태그에 dataset을 추가해서 event.target.dataId === 'accordionAnchor' 요런 느낌으로 할 수 있지 않을까요?

2024-06-13 16:57 UTC, hwangstar156 commented on app/_shared/accordion/accordion-title.tsx
> +      <AccordionTitleContainer expand={isExpand ?? true}>{children}</AccordionTitleContainer>
isExpand 초기값이 true면 문제없지 않을까요?

2024-06-13 16:57 UTC, hwangstar156 commented on app/_shared/heading/heading.tsx
> +  transition: color 0.05s ease-in;
👍

2024-06-13 16:57 UTC, hwangstar156 commented on app/_shared/toc/toc-side.tsx
> +})<{ level: number }>`
여기서 shouldForwardProp을 이미 적용하셨군요! 👍👍

2024-06-13 16:57 UTC, hwangstar156 commented on app/_shared/toc/toc-side.tsx
> +      if (!headingTops || headingTops.length === 0) return
이것도 block문으로 적는 걸 추천해요

```suggestion
      if (!headingTops || headingTops.length === 0) {
        return;
      }
```

2024-06-13 16:57 UTC, hwangstar156 commented on app/_shared/toc/toc-side.tsx
> +    }
scroll event listener의 passive 속성을 한번 알아보실래요? 성능에 도움이 되는 친구랍니다.

2024-06-13 16:57 UTC, hwangstar156 commented on app/_shared/toc/toc-side.tsx
> +    }
추가적으로 쓰로틀링도 함께 적용됬으면 하네용

2024-06-13 16:57 UTC, hwangstar156 commented on app/_shared/toc/toc-side.tsx
> +        }
if else가 여러겹 사용될때는 else 대신 early return으로 조금 가독성 좋게 처리할 수 있을거 같아요

2024-06-13 16:57 UTC, hwangstar156 commented on app/_shared/toc/toc-side.tsx
> +  }, [headingTops])
headingTops가 바뀔때마다 저 이벤트 핸들러를 초기화하는건 별로 좋아보이지 않네요. 저 함수를 실행시키는 것을 headingTops에 의존성이 있는 useEffect에 넣고, 이벤트 핸들러 초기화하는 로직은 mount 될때만 실행되게 하면 좋을 것 같아요

2024-06-13 16:57 UTC, hwangstar156 commented on app/_shared/toc/toc-side.tsx
> +                  data-level={toc.level}
여기서 data-level이 있는 이유는 뭘까요? 딱히 dataset으로 참조하는 곳은 없어보여서요

2024-06-13 16:57 UTC, hwangstar156 commented on app/_shared/toc/toc-side.tsx
> +export default TocSide
이미 named export 한 것을 또 default export 할 필요 없어보이는데 named export로 통일할까요?

2024-06-13 16:57 UTC, hwangstar156 commented on app/_shared/toc/toc-side.tsx
> +export const TocSide = ({ tableOfContents }: TocSideProps) => {
함수 선언식으로 하면 어떨까요? `export function TocSide() {}`

2024-06-13 16:57 UTC, hwangstar156 commented on app/_shared/toc/toc-side.tsx
> +    }
resize debouncing은 좋은 선택이네요

2024-06-13 16:57 UTC, hwangstar156 commented on app/_shared/toc/toc-side.tsx
> +  const settingHeadingTops = useCallback(() => {
useCallback은 성능에 문제있는거 아니면 어지간해서 안써도 됩니당. 최적화도 모두 비용이기 때문에 오히려 성능이 더 안 좋아질 수 도 있고용

그리고 tableOfContents가 배열이라서 의존성 배열에 들어가도 딱히 useCallback이 제대로 동작할 거 같지않네용.
useEffect의 dependency array는 Object.is()로 동작한답니당

2024-06-13 16:57 UTC, hwangstar156 commented on app/_shared/toc/toc-side.tsx
> +}
I prefix는 헝가리식 표현법이라고 이것이 Interface라는 것을 나타내는 것인데 요즘은 잘 사용하지 않는 표기법이에요. interface라는 것을 이미 `interface`라는 문법으로 알려주고 있으니까요. 오히려 이는 변수명을 쓸데없이 길게 만들고 한번에 의미를 파악하기 쉽지 않게 만들 수 있어용

2024-06-13 16:57 UTC, hwangstar156 commented on app/lib/auto-link-headings.ts
> +          node.children = [anchorLink, spaceNode, spanElement]
오호 👍👍 rehype에서 plugins로 제공하려면 고차함수 형태로 제공을 해야되나 보군요? 그렇다면 상위 함수와 하위 함수를 통일하는건 어떨까요?

둘 다 화살표함수거나, 함수 선언식이거나용

2024-06-13 16:57 UTC, hwangstar156 commented on app/lib/get-toc.ts
> +  ) as Array<1 | 2 | 3 | 4 | 5 | 6>
Array<1 | 2 | 3 | 4 | 5 | 6> 를 [1,2,3,4,5,6] 으로 대체할 수 있지 않을까요? 간단하게 ㅎㅎ

2024-06-13 16:57 UTC, hwangstar156 commented on app/lib/get-toc.ts
> +  ) as Array<1 | 2 | 3 | 4 | 5 | 6>
그리고 as 대신에 headerLevels에 바로 타입을 선언해도 될거 같네용

2024-06-13 16:57 UTC, hwangstar156 commented on app/lib/get-toc.ts
> +  ) as Array<1 | 2 | 3 | 4 | 5 | 6>
match.groups?.flag.length! -> 그리고 `!` 사용은 좋아보이지 않네용. 사용자 임의로 nullable한 값을 무시하는 거니까요. 이 부분은 타입가드를 이용하여 엄격하게 잡아봤으면 좋겠네요

2024-06-13 16:57 UTC, hwangstar156 commented on app/lib/get-toc.ts
> +    const min = sorted[0]
Math.min을 이용하면 하나로 줄여볼 수 있을거같네용

2024-06-13 16:57 UTC, hwangstar156 commented on app/lib/get-toc.ts
> +  const calculateHeaderLevels = (arr: Array<number>) => {
보통 Array<> 타입을 잘 사용하지 않습니당. 이런 경우는 number[] 표현법을 많이 이용합니당

2024-06-13 16:57 UTC, hwangstar156 commented on app/post/[topic]/components/container.tsx
> +  margin-right: auto;
margin: 5.5rem auto 0 auto로 써도 될거 같네용

2024-06-13 16:57 UTC, hwangstar156 commented on package.json
> +    "unist-util-visit": "^5.0.0"
이거 devdependencies에 있어도 되는 로직이려나요? 실제 런타임에서 사용하지 않나요? + github slugger, rehype, remark도 운영에 필요할 것 같네요

2024-06-13 16:57 UTC, hwangstar156 commented on app/_shared/toc/toc-side.tsx
> +  if (!document.body) return 0
위의 코멘트와 동일합니당

2024-06-13 16:57 UTC, hwangstar156 commented on app/_shared/toc/toc-side.tsx
> +  const settingHeadingTops = useCallback(() => {
+ 함수명은 setHeadingTops가 더 좋아보이네요.

2024-06-13 16:57 UTC, hwangstar156 commented on app/_shared/toc/toc-side.tsx
> +      const top = element ? element.getBoundingClientRect().top + scrollTop : Infinity
Infinity일때는 어떤 동작을 하는걸까요

2024-06-14 18:36 UTC, im-na0 reviewed
피드백 감사합니당 👍👍👍👍👍

toc-side에서 useEffect로 headingTop와 스크롤 위치 가져오는 부분을 맞게 고쳤는지를 모르겠네요 😓,, 한번 더 확인해주실 수 있을까요? ㅎㅎ

2024-06-14 18:36 UTC, im-na0 commented on app/_shared/toc/toc-side.tsx
> +      const top = element ? element.getBoundingClientRect().top + scrollTop : Infinity
요소가 없어서 Infinity가 될 때는
```ts
    const firstHeadingTop = headings[0].top // Infinity
    if (scrollTop < firstHeadingTop) {
      setActiveToc(headings[0].slug)
      return
    }
```
여기 if문에서 걸려서 비교 연산자를 통해 첫번째 헤딩의 toc만 활성화됩니당

2024-06-14 18:36 UTC, im-na0 commented on app/_shared/toc/toc-side.tsx
> +                  data-level={toc.level}
앗 data-level로 처리하려다가 level로 바꿨는데 삭제를 안했네요 삭제하겠습니다!

2024-06-14 18:45 UTC, hwangstar156 commented on app/_shared/accordion/accordion-title.tsx
> +      <AccordionTitleContainer expand={isExpand ?? true}>{children}</AccordionTitleContainer>
아하 객체로 관리되는 것이였군용. 지금 이렇게 가도 될거 같습니당~

2024-06-14 18:46 UTC, hwangstar156 commented on app/_shared/toc/toc-side.tsx
> +  const settingHeadingTops = useCallback(() => {
넵 그래도 될거같네영

2024-06-14 18:52 UTC, hwangstar156 commented on app/_shared/toc/toc-side.tsx
> +  }, [onScroll])
onScroll을 useEffect안에 넣고, useCallback을 제거한뒤에 dependency array도 빈배열로 관리되는게 좋을 거 같아요

2024-06-14 18:52 UTC, hwangstar156 commented on app/_shared/toc/toc-side.tsx
> +  }, [setHeadingTops])
위의 리뷰와 동일하게 setHeadingTops를 useEffect안에 넣고 useCallback 제거 후 dependency array도 빈배열로 처리해주시면 될 거 같아요

2024-06-14 19:39 UTC, im-na0 commented on app/_shared/toc/toc-side.tsx
> +  }, [onScroll])
onScroll를 useEffect에 넣고 dependency array도 빈배열로 했을 때 
headingTops가 초기화되지 않은 상태에서 useEffect가 실행되는 문제가 있네용 ..!

headingTops의 값이 업데이트 된 후에 useEffect가 실행되게 해야할 것 같은데 

```ts
  useEffect(() => {
    const onScroll = () => {
      const scrollTop = getScrollTop()

      if (!headingTops || headingTops.length === 0) {
        return
      }

      const firstHeadingTop = headingTops[0].top
      if (scrollTop < firstHeadingTop) {
        // 스크롤 위치가 첫 번째 헤딩의 스크롤 위치 보다 작거나 같으면 첫 번째 헤딩 활성화
        setActiveToc(headingTops[0].slug)
        return
      }

      const currentHeading = headingTops
        .slice()
        .reverse()
        .find((headingTop) => scrollTop >= headingTop.top - 10)

      setActiveToc(currentHeading ? currentHeading.slug : '')
    }

    onScroll()

    // TODO: 쓰로틀링 적용해보기
    window.addEventListener('scroll', onScroll, { passive: true })

    return () => {
      window.removeEventListener('scroll', onScroll)
    }
  }, [headingTops])
```
저는 의존성 배열에 headingTops를 추가하는 방법말곤 생각나는게 없네용 혹시 더 효율적인 방법이 있을까용?? 🧐

2024-06-15 06:37 UTC, im-na0 commented on app/_shared/toc/toc-side.tsx
> +  }, [onScroll])
![스크린샷 2024-06-15 오후 2 17 43](https://github.com/dev-wiki-kr/dev-wiki/assets/139189221/5ff65750-b4fb-4d88-8251-cfbc9161feeb)
addEventListener, removeEventListener 각각 위에서 로그 찍어봤을 때
초기화될 때 스크롤 이벤트가 한번만 등록되는 거 확인했습니당

@hwangstar156

2024-06-15 14:59 UTC, hwangstar156 approved these changes

2024-06-21 15:43 UTC, hwangstar156 commented
머지할게용~

2024-06-21 15:43 UTC, merged