feat: page 하단 author, contributor ui 제작
dev-wiki-kr/dev-wiki pull request #88
Opened 2024-08-16 13:36 UTC by chaduhwan

## 설명
글 page 하단에 작성자 author 및 기여자 contributor ui를 제작하였습니다.

## 변경 내역
작성자 author는 필수적으로 표시되며 최초작성자라는 태그가 같이 표시됩니다.
작성자 및 기여자의 수가 6명 이하일시 더보기 버튼이 보이지 않습니다.

## 논의할 점
더보기를 클릭할 시 몇개의 기여자가 더보이게 해야하는지 ? 
=> 현재는 클릭시 5명 이후의 나머지 기여자들이 모두 보입니다.

## 스크린샷

# 5명 이상의 기여자가 포함될 떄
https://github.com/user-attachments/assets/318683c0-603a-4ce2-b96e-ccbe34b48aa6

# 작성자만 있을 때
<img width="1016" alt="스크린샷 2024-08-16 오후 10 26 08" src="https://github.com/user-attachments/assets/d7ebaffb-b803-4873-ba21-d4f9d3e706d1">

2024-08-31 10:05 UTC, hwangstar156 requested changes

2024-08-31 10:05 UTC, hwangstar156 commented on app/post/[topic]/components/author+contributor/author-info.tsx
> +}
interface 네이밍은 component name + props어떨까요?

AuthorInfoProps가 되겠네요

2024-08-31 10:05 UTC, hwangstar156 commented on app/post/[topic]/components/author+contributor/author.tsx
> +  }
이러한 이벤트핸들러는 화살표함수로 통일합시다! + 위의 isOpen과 아래의 return에 각각 한칸 띄워주세요~

2024-08-31 10:05 UTC, hwangstar156 commented on app/post/[topic]/components/author+contributor/author.tsx
> +        <AuthorInfo src={authorData!.avartarUrl!} username={authorData.username!} />
이런 !와 같은 타입단언은 좋지 않아보이네요. `authorData?.avartarUrl ?? ''` 이게 더 괜찮아 보입니다. username도 동일합니다!

2024-08-31 10:05 UTC, hwangstar156 commented on app/post/[topic]/components/author+contributor/author.tsx
> +      {showAll && <ShowMore onClick={handleOpen}>더 보기 ↓</ShowMore>}
이 default 화살표 아이콘을 쓰기에는 별로네요. 실제 figma의 icon을 export해와서 쓰면 좋을 것 같네요. 이거는 추후 제가 cdn작업을 한후 해보도록 하죠.

2024-08-31 10:05 UTC, hwangstar156 commented on app/post/[topic]/page.tsx
> +import { Author } from './components/author+contributor/author'
지금 확인했는데 이 +가 들어가있는 파일네임의 정체는 뭘까요..?

2024-08-31 10:05 UTC, hwangstar156 commented on app/post/[topic]/page.tsx
> +      <Author authorData={author!} contributorData={contributors} />
여기도 타입단언이 있네요.

2024-09-27 09:38 UTC, chaduhwan reviewed
늦어서 죄송합니다 ^^ ㅜ

2024-09-27 09:38 UTC, chaduhwan commented on app/post/[topic]/components/author+contributor/author-info.tsx
> +}
넵 ㅎㅎ .. 생각이 좀 짧았네요 이건

2024-09-27 11:26 UTC, chaduhwan commented on app/post/[topic]/components/author+contributor/author.tsx
> +        <AuthorInfo src={authorData!.avartarUrl!} username={authorData.username!} />
타입 단언 빼겟습니다 !

2024-09-27 11:26 UTC, chaduhwan commented on app/post/[topic]/page.tsx
> +import { Author } from './components/author+contributor/author'
작성자+기여자를 표현할려고했는데 더 좋은 방법 있을까요 .....

2024-09-27 11:26 UTC, chaduhwan commented on app/post/[topic]/page.tsx
> +      <Author authorData={author!} contributorData={contributors} />
여기도 빼겠습니다 !

2024-09-28 06:18 UTC, hwangstar156 commented on app/post/[topic]/page.tsx
> +import { Author } from './components/author+contributor/author'
그냥 author로만 하시죠

2024-09-28 06:19 UTC, hwangstar156 commented on app/post/[topic]/page.tsx
> +import { Author } from './components/author+contributor/author'
이미 바꾸셨군요 👍

2024-09-28 06:19 UTC, hwangstar156 approved these changes

2024-09-28 06:20 UTC, hwangstar156 commented
머지할게요~

2024-09-28 06:20 UTC, merged